<?php

namespace Application\Utility\Rendering;

use Application\Utility\Authentication\CMUser;
use JasperFW\JasperFW\Lifecycle\Response;
use JasperFW\JasperFW\Renderer\TwigRenderer;

class CMTwigRenderer extends TwigRenderer
{
    public function render(Response $response): void
    {
        $response->setValue('username', CMUser::i()->getUsername());
        $response->setValue('userid', CMUser::i()->getUserID());
        $response->setValue('usertype', CMUser::i()->getUserType());
        parent::render($response); // TODO: Change the autogenerated stub
    }
}